# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-827a829d-8070-4986-a280-8a64e021a713";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-827a829d-8070-4986-a280-8a64e021a713".device =
    "/dev/disk/by-uuid/827a829d-8070-4986-a280-8a64e021a713";

  boot.initrd.luks.devices."luks-3b463890-63a7-4261-8108-955e71cd23d6".device =
    "/dev/disk/by-uuid/3b463890-63a7-4261-8108-955e71cd23d6";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4064-D98C";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-3b463890-63a7-4261-8108-955e71cd23d6"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
